version: '3.8'
services:
  api:
    build: ./api
    image: careercanvas-api
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=...
      - JWT_SECRET=...

  admin-dashboard:
    build: ./admin
    image: careercanvas-admin
    deploy:
      replicas: 2
    environment:
      - NODE_ENV=production
      - API_URL=https://api.careercanvas.pro

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt