version: '3.8'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secure_password

  elasticsearch:
    image: elasticsearch:8.7.0
    environment:
      - discovery.type=single-node

  kibana:
    image: kibana:8.7.0
    ports:
      - "5601:5601"