name: Deploy CareerCanvas

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build and Test API
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet test
      
      - name: Build Admin Dashboard
        run: |
          cd admin
          npm install
          npm run build
      
      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: |
          docker-compose -f deploy/docker-compose.yml build
          docker-compose -f deploy/docker-compose.yml push